/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orders;

import assignment.success;
import deliveryStaff.manageTasks;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import managingStaff.edit;

/**
 *
 * @author bidha
 */
public class allOrdersTable extends javax.swing.JFrame {

    /**
     * Creates new form allOrdersTable
     */
    public allOrdersTable() {
        initComponents();
        allordetable.setAutoCreateRowSorter(true);
    }
public void searchintable(String str){
        DefaultTableModel model = (DefaultTableModel)allordetable.getModel();
        TableRowSorter<DefaultTableModel> ts=new TableRowSorter<>(model);
       allordetable.setRowSorter(ts);
        ts.setRowFilter(RowFilter.regexFilter(str));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        allordetable = new javax.swing.JTable();
        n1 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tosearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 63, 107));

        jLabel4.setBackground(new java.awt.Color(255, 198, 0));
        jLabel4.setFont(new java.awt.Font("Poppins ExtraBold", 0, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 198, 0));
        jLabel4.setText("ORDERS TABLE");

        back.setBackground(new java.awt.Color(235, 29, 54));
        back.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 198, 0));
        back.setText("BACK");
        back.setAlignmentX(0.5F);
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        allordetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATE", "SNAME", "", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "RNAME", "PHONE", "EMAIL", "STREET", "CITY", "MUNICIPALITY", "DISTRICT", "PROVINCE", "LENGTH", "WIDTH", "HEIGHT", "WEIGHT", "FEES", "null", "LOCATION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allordetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allordetableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allordetableMouseEntered(evt);
            }
        });
        allordetable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                allordetableKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                allordetableKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(allordetable);
        if (allordetable.getColumnModel().getColumnCount() > 0) {
            allordetable.getColumnModel().getColumn(2).setMinWidth(0);
            allordetable.getColumnModel().getColumn(2).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(2).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(3).setMinWidth(0);
            allordetable.getColumnModel().getColumn(3).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(3).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(4).setMinWidth(0);
            allordetable.getColumnModel().getColumn(4).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(4).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(5).setMinWidth(0);
            allordetable.getColumnModel().getColumn(5).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(5).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(6).setMinWidth(0);
            allordetable.getColumnModel().getColumn(6).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(6).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(7).setMinWidth(0);
            allordetable.getColumnModel().getColumn(7).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(7).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(8).setMinWidth(0);
            allordetable.getColumnModel().getColumn(8).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(8).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(9).setMinWidth(0);
            allordetable.getColumnModel().getColumn(9).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(9).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(12).setMinWidth(0);
            allordetable.getColumnModel().getColumn(12).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(12).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(13).setMinWidth(0);
            allordetable.getColumnModel().getColumn(13).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(13).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(14).setMinWidth(0);
            allordetable.getColumnModel().getColumn(14).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(14).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(15).setMinWidth(0);
            allordetable.getColumnModel().getColumn(15).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(15).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(17).setMinWidth(0);
            allordetable.getColumnModel().getColumn(17).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(17).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(18).setMinWidth(0);
            allordetable.getColumnModel().getColumn(18).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(18).setMaxWidth(0);
            allordetable.getColumnModel().getColumn(23).setMinWidth(0);
            allordetable.getColumnModel().getColumn(23).setPreferredWidth(0);
            allordetable.getColumnModel().getColumn(23).setMaxWidth(0);
        }

        n1.setBackground(new java.awt.Color(255, 183, 43));
        n1.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        n1.setText("WAREHOUSE A");
        n1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        buttonGroup1.add(n1);
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });

        n2.setBackground(new java.awt.Color(255, 183, 43));
        n2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        n2.setText("SHIPPING");
        n2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        buttonGroup1.add(n2);
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });

        n3.setBackground(new java.awt.Color(255, 183, 43));
        n3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        n3.setText("WAREHOUSE B");
        n3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        n3.setBorderPainted(false);
        buttonGroup1.add(n3);
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });

        n4.setBackground(new java.awt.Color(255, 183, 43));
        n4.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        n4.setText("OFFICE B");
        n4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        buttonGroup1.add(n4);
        n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4ActionPerformed(evt);
            }
        });

        n5.setBackground(new java.awt.Color(255, 183, 43));
        n5.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        n5.setText("START DELIVERY");
        n5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        buttonGroup1.add(n5);
        n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 198, 0));
        jLabel5.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 198, 0));
        jLabel5.setText("SEARCH");

        tosearch.setBackground(new java.awt.Color(246, 245, 77));
        tosearch.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
        tosearch.setForeground(new java.awt.Color(0, 0, 0));
        tosearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tosearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tosearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n1)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 337, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tosearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tosearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        new checkInOrders().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void allordetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allordetableMouseClicked
        orderplace showorders=new orderplace();
        showorders.setVisible(true);
        showorders.order.setVisible(false);
        showorders.jButtonback.setVisible(false);
        showorders.jButtonback1.setVisible(true);
        int index=allordetable.getSelectedRow();
        TableModel model=allordetable.getModel();
        String ID=model.getValueAt(index,0).toString();
        String SNAME=model.getValueAt(index,2).toString();
        String SPHONE=model.getValueAt(index,3).toString();
        String SEMAIL=model.getValueAt(index,4).toString();
        String SSTREET=model.getValueAt(index,5).toString();
        String STOWN=model.getValueAt(index,6).toString();
        String SMUNI=model.getValueAt(index,7).toString();
        String SDISTRICT=model.getValueAt(index,8).toString();
        String SPROVINCE=model.getValueAt(index,9).toString();
        String DATE=model.getValueAt(index,1).toString();
        String RNAME=model.getValueAt(index,10).toString();
        String RPHONE=model.getValueAt(index,11).toString();
        String REMAIL=model.getValueAt(index,12).toString();
        String RSTREET=model.getValueAt(index,13).toString();
        String RTOWN=model.getValueAt(index,14).toString();
        String RMUNI=model.getValueAt(index,15).toString();
        String RDISTRICT=model.getValueAt(index,16).toString();
        String RPROVINCE=model.getValueAt(index,17).toString();
        String L=model.getValueAt(index,18).toString();
        String B=model.getValueAt(index,19).toString();
        String H=model.getValueAt(index,20).toString();
        String W=model.getValueAt(index,21).toString();
        String FEES=model.getValueAt(index,22).toString();
        String STATUS=model.getValueAt(index,23).toString();
        String LOCATION=model.getValueAt(index,24).toString();
        showorders.pack();
        showorders.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        showorders.id.setText(ID);showorders.id.setEditable(false);
        showorders.date.setText(DATE);showorders.date.setEditable(false);
        showorders.sname.setText(SNAME);showorders.sname.setEditable(false);
        showorders.sphone.setText(SPHONE);showorders.sphone.setEditable(false);
        showorders.semail.setText(SEMAIL);showorders.semail.setEditable(false);
        showorders.sstreet.setText(SSTREET);showorders.sstreet.setEditable(false);
        showorders.scity.setText(STOWN);showorders.scity.setEditable(false);
        showorders.sdistrict.setText(SDISTRICT);showorders.sdistrict.setEditable(false);
        showorders.sprovince.setText(SPROVINCE);showorders.sprovince.setEditable(false);
        showorders.rmuni.setText(RMUNI);showorders.rmuni.setEditable(false);
        showorders.rname.setText(RNAME);showorders.rname.setEditable(false);
        showorders.smuni.setText(SMUNI);showorders.smuni.setEditable(false);
        showorders.rphone.setText(RPHONE);showorders.rphone.setEditable(false);
        showorders.remail.setText(REMAIL);showorders.remail.setEditable(false);
        showorders.rstreet.setText(RSTREET);showorders.rcity.setEditable(false);
        showorders.rcity.setText(RTOWN);showorders.rdistrict.setEditable(false);
        showorders.rdistrict.setText(RDISTRICT);showorders.rcity.setEditable(false);
        showorders.rprovince.setText(RPROVINCE);showorders.rprovince.setEditable(false);
        showorders.rmuni.setText(RMUNI);showorders.rmuni.setEditable(false);
        showorders.length.setText(L);showorders.length.setEditable(false);
        showorders.breadth.setText(B);showorders.breadth.setEditable(false);
        showorders.height.setText(H);showorders.height.setEditable(false);
        showorders.weight.setText(W);showorders.weight.setEditable(false);
        showorders.fees.setText(FEES);showorders.fees.setEditable(false); 
    }//GEN-LAST:event_allordetableMouseClicked

    private void allordetableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allordetableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_allordetableMouseEntered

    private void allordetableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_allordetableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_allordetableKeyPressed

    private void allordetableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_allordetableKeyTyped
        // TODO add your handling code here:
        

    }//GEN-LAST:event_allordetableKeyTyped

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        try {
            editLocation("warehouseA");
            
        } catch (IOException ex) {
            Logger.getLogger(allOrdersTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_n1ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        try {
            // TODO add your handling code here:
            editLocation("shipping");
        } catch (IOException ex) {
            Logger.getLogger(allOrdersTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_n2ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        try {
            // TODO add your handling code here:
            editLocation("warehouseB");
        } catch (IOException ex) {
            Logger.getLogger(allOrdersTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_n3ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
        try {
            // TODO add your handling code here:
            editLocation("officeB");
        } catch (IOException ex) {
            Logger.getLogger(allOrdersTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_n4ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
        try {
            // TODO add your handling code here:
            editLocation("deliverystart");
        } catch (IOException ex) {
            Logger.getLogger(allOrdersTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_n5ActionPerformed

    private void tosearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tosearchKeyReleased
        // TODO add your handling code here:
        String searchString=tosearch.getText();
        searchintable(searchString);
    }//GEN-LAST:event_tosearchKeyReleased
    
    public void editLocation(String keyword) throws IOException{
       
       int index=allordetable.getSelectedRow();
        TableModel model=allordetable.getModel();
        String id=model.getValueAt(index,0).toString();
         String ID,DATE,NAME1,PHONE1,EMAIL1,STREET1,CITY1,MUNI1,DISTRICT1,PROVINCE1,
                    NAME2,PHONE2,EMAIL2,STREET2,CITY2,MUNI2,DISTRICT2,PROVINCE2,L,B ,H ,W,FEES,STATUS,LOCATION;
        String tempFile="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\temp.txt";
       String path="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt";
        File oldFile = new File(path);
       File newFile=new File(tempFile);
       FileWriter fw;
            fw = new FileWriter(tempFile,true);
            BufferedWriter bw=new BufferedWriter(fw);
           try (PrintWriter pw = new PrintWriter(bw)) {
               x=new Scanner(new File(path));
               x.useDelimiter("[,\n]");
               while(x.hasNext()){
                   ID=x.next();DATE=x.next();                  
                   NAME1=x.next();PHONE1=x.next();
                   EMAIL1=x.next();STREET1=x.next();
                   CITY1=x.next();MUNI1=x.next();
                   DISTRICT1=x.next();PROVINCE1=x.next();
                   NAME2=x.next();PHONE2=x.next();
                   EMAIL2=x.next();STREET2=x.next();
                   CITY2=x.next();MUNI2=x.next();
                   DISTRICT2=x.next();PROVINCE2=x.next();
                   L=x.next();B=x.next();
                   H=x.next();W=x.next();
                   FEES=x.next();STATUS=x.next();LOCATION=x.next();
                   if(ID.equals(id)){
                       pw.print(ID + "," + DATE+","+NAME1+","+PHONE1+","+EMAIL1+","+STREET1+","+CITY1+","+MUNI1+","+DISTRICT1+","+PROVINCE1+","+
                    NAME2+","+PHONE2+","+EMAIL2+","+STREET2+","+CITY2+","+MUNI2+","+DISTRICT2+","+PROVINCE2+","+L+","+B+","+H+","+W+","+FEES+","+STATUS+","+keyword+"\n");
                   }
                   else{
                       pw.print(ID + "," + DATE+","+NAME1+","+PHONE1+","+EMAIL1+","+STREET1+","+CITY1+","+MUNI1+","+DISTRICT1+","+PROVINCE1+","+
                    NAME2+","+PHONE2+","+EMAIL2+","+STREET2+","+CITY2+","+MUNI2+","+DISTRICT2+","+PROVINCE2+","+L+","+B+","+H+","+W+","+FEES+","+STATUS+","+LOCATION+"\n");
                   }
               }x.close();
        pw.flush();
        pw.close();
        oldFile.delete();
        
        File dump=new File(path);
        newFile.renameTo(dump);
        new success().setVisible(true);
           
        } catch (IOException ex) {
            Logger.getLogger(edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public String todaydate(){
         Calendar cal = Calendar.getInstance(); 
        Date d = new Date();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        String date1=sdf1.format(d);
       
        return date1;
    }
            
    private Scanner x;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allOrdersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allOrdersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allOrdersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allOrdersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allOrdersTable().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable allordetable;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton n1;
    public javax.swing.JButton n2;
    public javax.swing.JButton n3;
    public javax.swing.JButton n4;
    public javax.swing.JButton n5;
    public javax.swing.JTextField tosearch;
    // End of variables declaration//GEN-END:variables
}
