/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orders;

import assignment.success;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import managingStaff.dashboardManagingStaff;
import managingStaff.edit;
import managingStaff.viewIndi;
import managingStaff.viewUser;
import myproject.AssignTask;

/**
 *
 * @author bidha
 */
public final class assignTask extends javax.swing.JFrame {
viewUser deliveryTable=new viewUser();
String selectedOID,selectedRname,selectedPhone,selectedEmail,selectedStreet,selectedCity,selectedMuni,selectedDis,selectedProvince;
String theID,selectedfname,selectedsname,selectednum,selectedemail;
    /**
     * Creates new form assignTask
     */
    public assignTask() throws IOException {
        initComponents();
        orderTable(23,"toassign");
        showdelivery();
        detailstable.setAutoCreateRowSorter(true);
        ordertable.setAutoCreateColumnsFromModel(true);
        
    }
public void searchintable(String str, JTable tablename){
        DefaultTableModel model = (DefaultTableModel)tablename.getModel();
        TableRowSorter<DefaultTableModel> ts=new TableRowSorter<>(model);
       tablename.setRowSorter(ts);
        ts.setRowFilter(RowFilter.regexFilter(str));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailstable = new javax.swing.JTable();
        assign = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        tosearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tosearch1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 63, 107));

        jLabel4.setBackground(new java.awt.Color(255, 198, 0));
        jLabel4.setFont(new java.awt.Font("Poppins ExtraBold", 0, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 198, 0));
        jLabel4.setText("ASSIGN TASKS");

        back.setBackground(new java.awt.Color(235, 29, 54));
        back.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 198, 0));
        back.setText("BACK");
        back.setAlignmentX(0.5F);
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATE", "SNAME", "", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "RNAME", "PHONE", "EMAIL", "STREET", "CITY", "MUNICIPALITY", "DISTRICT", "PROVINCE", "LENGTH", "WIDTH", "HEIGHT", "WEIGHT", "FEES", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordertableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordertableMouseEntered(evt);
            }
        });
        ordertable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ordertableKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ordertableKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(ordertable);
        if (ordertable.getColumnModel().getColumnCount() > 0) {
            ordertable.getColumnModel().getColumn(2).setMinWidth(0);
            ordertable.getColumnModel().getColumn(2).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(2).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(3).setMinWidth(0);
            ordertable.getColumnModel().getColumn(3).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(3).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(4).setMinWidth(0);
            ordertable.getColumnModel().getColumn(4).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(4).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(5).setMinWidth(0);
            ordertable.getColumnModel().getColumn(5).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(5).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(6).setMinWidth(0);
            ordertable.getColumnModel().getColumn(6).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(6).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(7).setMinWidth(0);
            ordertable.getColumnModel().getColumn(7).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(7).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(8).setMinWidth(0);
            ordertable.getColumnModel().getColumn(8).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(8).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(9).setMinWidth(0);
            ordertable.getColumnModel().getColumn(9).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(9).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(18).setMinWidth(0);
            ordertable.getColumnModel().getColumn(18).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(18).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(19).setMinWidth(0);
            ordertable.getColumnModel().getColumn(19).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(19).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(20).setMinWidth(0);
            ordertable.getColumnModel().getColumn(20).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(20).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(21).setMinWidth(0);
            ordertable.getColumnModel().getColumn(21).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(21).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(22).setMinWidth(0);
            ordertable.getColumnModel().getColumn(22).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(22).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(23).setMinWidth(0);
            ordertable.getColumnModel().getColumn(23).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(23).setMaxWidth(0);
            ordertable.getColumnModel().getColumn(24).setMinWidth(0);
            ordertable.getColumnModel().getColumn(24).setPreferredWidth(0);
            ordertable.getColumnModel().getColumn(24).setMaxWidth(0);
        }

        detailstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ROLE", "FIRST NAME", "SECOND NAME", "DAY", "MONTH", "YEAR", "GENDER", "STREET", "TOWN", "CITY", "DISTRTICT", "PROVINCE", "PHONE", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detailstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailstableMouseClicked(evt);
            }
        });
        detailstable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                detailstableKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(detailstable);
        if (detailstable.getColumnModel().getColumnCount() > 0) {
            detailstable.getColumnModel().getColumn(1).setMinWidth(0);
            detailstable.getColumnModel().getColumn(1).setPreferredWidth(0);
            detailstable.getColumnModel().getColumn(1).setMaxWidth(0);
            detailstable.getColumnModel().getColumn(4).setMinWidth(0);
            detailstable.getColumnModel().getColumn(4).setPreferredWidth(0);
            detailstable.getColumnModel().getColumn(4).setMaxWidth(0);
            detailstable.getColumnModel().getColumn(5).setMinWidth(0);
            detailstable.getColumnModel().getColumn(5).setPreferredWidth(0);
            detailstable.getColumnModel().getColumn(5).setMaxWidth(0);
            detailstable.getColumnModel().getColumn(6).setMinWidth(0);
            detailstable.getColumnModel().getColumn(6).setPreferredWidth(0);
            detailstable.getColumnModel().getColumn(6).setMaxWidth(0);
            detailstable.getColumnModel().getColumn(8).setMinWidth(0);
            detailstable.getColumnModel().getColumn(8).setPreferredWidth(0);
            detailstable.getColumnModel().getColumn(8).setMaxWidth(0);
            detailstable.getColumnModel().getColumn(9).setMinWidth(0);
            detailstable.getColumnModel().getColumn(9).setPreferredWidth(0);
            detailstable.getColumnModel().getColumn(9).setMaxWidth(0);
            detailstable.getColumnModel().getColumn(10).setMinWidth(0);
            detailstable.getColumnModel().getColumn(10).setPreferredWidth(0);
            detailstable.getColumnModel().getColumn(10).setMaxWidth(0);
            detailstable.getColumnModel().getColumn(11).setMinWidth(0);
            detailstable.getColumnModel().getColumn(11).setPreferredWidth(0);
            detailstable.getColumnModel().getColumn(11).setMaxWidth(0);
            detailstable.getColumnModel().getColumn(12).setMinWidth(0);
            detailstable.getColumnModel().getColumn(12).setPreferredWidth(0);
            detailstable.getColumnModel().getColumn(12).setMaxWidth(0);
        }

        assign.setBackground(new java.awt.Color(255, 183, 43));
        assign.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        assign.setText("ASSIGN");
        assign.setBorder(null);
        assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 198, 0));
        jLabel5.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 198, 0));
        jLabel5.setText("SEARCH");

        tosearch.setBackground(new java.awt.Color(246, 245, 77));
        tosearch.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
        tosearch.setForeground(new java.awt.Color(0, 0, 0));
        tosearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tosearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tosearchKeyReleased(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 198, 0));
        jLabel6.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 198, 0));
        jLabel6.setText("SEARCH");

        tosearch1.setBackground(new java.awt.Color(246, 245, 77));
        tosearch1.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
        tosearch1.setForeground(new java.awt.Color(0, 0, 0));
        tosearch1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tosearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tosearch1KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 29, 54));
        jLabel1.setText("*Press ENTER to view details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(284, 284, 284)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(assign, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tosearch, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tosearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tosearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tosearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(assign, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new dashboardManagingStaff().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void detailstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailstableMouseClicked
        int index=detailstable.getSelectedRow();
        TableModel model=detailstable.getModel();
        theID=model.getValueAt(index,0).toString();
        selectedfname=model.getValueAt(index,2).toString();
        selectedsname=model.getValueAt(index,3).toString();
        selectednum=model.getValueAt(index,13).toString();
        selectedemail=model.getValueAt(index,14).toString();   
    }//GEN-LAST:event_detailstableMouseClicked

    private void ordertableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordertableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ordertableMouseEntered

    private void ordertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordertableMouseClicked
        // TODO add your handling code here:
        int index=ordertable.getSelectedRow();
        TableModel model=ordertable.getModel();
        selectedOID=model.getValueAt(index,0).toString();
        selectedRname=model.getValueAt(index,10).toString();
        selectedPhone=model.getValueAt(index,11).toString();
        selectedEmail=model.getValueAt(index,12).toString();
        selectedStreet=model.getValueAt(index,13).toString();
        selectedCity=model.getValueAt(index,14).toString();
        selectedMuni=model.getValueAt(index,15).toString();
        selectedDis=model.getValueAt(index,16).toString();
        selectedProvince=model.getValueAt(index,17).toString();
    }//GEN-LAST:event_ordertableMouseClicked

    private void ordertableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ordertableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordertableKeyPressed

    private void ordertableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ordertableKeyTyped
        // TODO add your handling code here:
        showform();
        
    }//GEN-LAST:event_ordertableKeyTyped
public void showform(){
        orderplace showorders=new orderplace();
        showorders.setVisible(true);
        showorders.order.setVisible(false);
        showorders.jButtonback.setVisible(false);
        showorders.jButtonback1.setVisible(true);
        int index=ordertable.getSelectedRow();
        TableModel model=ordertable.getModel();
        String ID=model.getValueAt(index,0).toString();
        String SNAME=model.getValueAt(index,1).toString();
        String SPHONE=model.getValueAt(index,3).toString();
        String SEMAIL=model.getValueAt(index,4).toString();
        String SSTREET=model.getValueAt(index,5).toString();
        String STOWN=model.getValueAt(index,6).toString();
        String SMUNI=model.getValueAt(index,7).toString();
        String SDISTRICT=model.getValueAt(index,8).toString();
        String SPROVINCE=model.getValueAt(index,9).toString();
        String DATE=model.getValueAt(index,2).toString();
        String RNAME=model.getValueAt(index,10).toString();
        String RPHONE=model.getValueAt(index,11).toString();
        String REMAIL=model.getValueAt(index,12).toString();
        String RSTREET=model.getValueAt(index,13).toString();
        String RTOWN=model.getValueAt(index,14).toString();
        String RMUNI=model.getValueAt(index,15).toString();
        String RDISTRICT=model.getValueAt(index,16).toString();
        String RPROVINCE=model.getValueAt(index,17).toString();
        String L=model.getValueAt(index,18).toString();
        String B=model.getValueAt(index,19).toString();
        String H=model.getValueAt(index,20).toString();
        String W=model.getValueAt(index,21).toString();
        String FEES=model.getValueAt(index,22).toString();
        String STATUS=model.getValueAt(index,23).toString();
        String LOCATION=model.getValueAt(index,24).toString();
        showorders.pack();
        showorders.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        showorders.id.setText(ID);showorders.id.setEditable(false);
        showorders.date.setText(DATE);showorders.date.setEditable(false);
        showorders.sname.setText(SNAME);showorders.sname.setEditable(false);
        showorders.sphone.setText(SPHONE);showorders.sphone.setEditable(false);
        showorders.semail.setText(SEMAIL);showorders.semail.setEditable(false);
        showorders.sstreet.setText(SSTREET);showorders.sstreet.setEditable(false);
        showorders.scity.setText(STOWN);showorders.scity.setEditable(false);
        showorders.sdistrict.setText(SDISTRICT);showorders.sdistrict.setEditable(false);
        showorders.sprovince.setText(SPROVINCE);showorders.sprovince.setEditable(false);
        showorders.rmuni.setText(RMUNI);showorders.rmuni.setEditable(false);
        showorders.rname.setText(RNAME);showorders.rname.setEditable(false);
        showorders.smuni.setText(SMUNI);showorders.smuni.setEditable(false);
        showorders.rphone.setText(RPHONE);showorders.rphone.setEditable(false);
        showorders.remail.setText(REMAIL);showorders.remail.setEditable(false);
        showorders.rstreet.setText(RSTREET);showorders.rcity.setEditable(false);
        showorders.rcity.setText(RTOWN);showorders.rdistrict.setEditable(false);
        showorders.rdistrict.setText(RDISTRICT);showorders.rcity.setEditable(false);
        showorders.rprovince.setText(RPROVINCE);showorders.rprovince.setEditable(false);
        showorders.rmuni.setText(RMUNI);showorders.rmuni.setEditable(false);
        showorders.length.setText(L);showorders.length.setEditable(false);
        showorders.breadth.setText(B);showorders.breadth.setEditable(false);
        showorders.height.setText(H);showorders.height.setEditable(false);
        showorders.weight.setText(W);showorders.weight.setEditable(false);
        showorders.fees.setText(FEES);showorders.fees.setEditable(false);
       
}
    private void detailstableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detailstableKeyTyped
        // TODO add your handling code here:
        viewIndi jdata=new viewIndi();
        int index=detailstable.getSelectedRow();
        TableModel model=detailstable.getModel();
        String eid=model.getValueAt(index,0).toString();
        String erole=model.getValueAt(index,1).toString();
        String efname=model.getValueAt(index,2).toString();
        String esname=model.getValueAt(index,3).toString();
        String eday=model.getValueAt(index,4).toString();
        String emonth=model.getValueAt(index,5).toString();
        String eyear=model.getValueAt(index,6).toString();
        String egender=model.getValueAt(index,7).toString();
        String estreet=model.getValueAt(index,8).toString();
        String etown=model.getValueAt(index,9).toString();
        String ecity=model.getValueAt(index,10).toString();
        String edistrict=model.getValueAt(index,11).toString();
        String eprovince=model.getValueAt(index,12).toString();
        String enumber=model.getValueAt(index,13).toString();
        String eemail=model.getValueAt(index,14).toString();
        
        jdata.setVisible(true);
        jdata.pack();
        jdata.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jdata.uid.setText(eid);
        jdata.roles.setText(erole);
        jdata.firstname.setText(efname);
        jdata.secondname.setText(esname);
        jdata.uday.setText(eday);
        jdata.umonth.setText(emonth);
        jdata.uyear.setText(eyear);
        jdata.sex.setText(egender);
        jdata.street.setText(estreet);
        jdata.city.setText(etown);
        jdata.municipality.setText(ecity);
        jdata.district.setText(edistrict);
        jdata.province.setText(eprovince);
        jdata.phone.setText(enumber);
        jdata.email.setText(eemail);
        
    }//GEN-LAST:event_detailstableKeyTyped

    private void assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignActionPerformed
        // TODO add your handling code here:
       File file2=new File("C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\deliverydetails.txt");
        try {
            BufferedWriter bw2=new BufferedWriter(new FileWriter(file2,true));
            String line2=selectedOID+","+selectedRname+","+selectedPhone+","+selectedEmail+","+selectedStreet+","+
                    selectedCity+","+selectedMuni+","+selectedDis+","+selectedProvince+","+theID+","+
                    selectedfname+","+selectedsname+","+selectednum+","+selectedemail+","+sendDate()+","+"toaccept"+"\n";
            bw2.write(line2);
            bw2.close();
            editdetails("toaccept",selectedOID);
            new success().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AssignTask.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
    }//GEN-LAST:event_assignActionPerformed

    private void tosearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tosearchKeyReleased
        // TODO add your handling code here:
        String searchString=tosearch.getText();
        searchintable(searchString,ordertable);
    }//GEN-LAST:event_tosearchKeyReleased

    private void tosearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tosearch1KeyReleased
        // TODO add your handling code here:
        String searchString=tosearch1.getText();
        searchintable(searchString,detailstable);
    }//GEN-LAST:event_tosearch1KeyReleased
  
    public void orderTable(int num,String keyword) throws FileNotFoundException, IOException{
        removerow();
        String filePath ="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt";
        File file = new File(filePath);
        FileReader fr = new FileReader(filePath);
       BufferedReader br = new BufferedReader(fr);
        DefaultTableModel model = (DefaultTableModel)ordertable.getModel();
        Object[] lines = br.lines().toArray();
    for (Object line : lines) {
        String[] row = line.toString().split(",");
        if(row[num].equals(keyword)&&row[24].equals("deliverystart")){//to add row[24].equals("officeB")
            model.addRow(row);}
    }
        br.close();
        fr.close();
    }
     public void removerow(){
         DefaultTableModel tbl=(DefaultTableModel)ordertable.getModel();
        int torem=ordertable.getRowCount();
        for (int i=torem-1;i>=0;i--){
            tbl.removeRow(i);
        }
    }
    public void showdelivery(){
        String filePath ="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\deliveryStaff\\deliveryboys.txt";
        
        File file = new File(filePath);
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            // get the first line
            // get the columns name from the first line
            // set columns name to the jtable model
            
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)detailstable.getModel();
            model.addRow(columnsName);
            // get lines from txt file
            Object[] tableLines = br.lines().toArray();
            br.close();
            
             
            
     // extratct data from lines
     // set data to jtable model
        for (Object tableLine : tableLines) {
            String line = tableLine.toString().trim();
            String[] dataRow = line.split(",");
            model.addRow(dataRow);
        }
            
            
       
        }
        catch (IOException ex) {
            Logger.getLogger(viewUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void editdetails(String keyword,String id) throws IOException{
       
        String ID,DATE,NAME1,PHONE1,EMAIL1,STREET1,CITY1,MUNI1,DISTRICT1,PROVINCE1,
                    NAME2,PHONE2,EMAIL2,STREET2,CITY2,MUNI2,DISTRICT2,PROVINCE2,L,B ,H ,W,FEES,STATUS,LOCATION;
        String tempFile="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\temp.txt";
       String path="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt";
        File oldFile = new File(path);
       File newFile=new File(tempFile);
       FileWriter fw;
            fw = new FileWriter(tempFile,true);
            BufferedWriter bw=new BufferedWriter(fw);
           try (PrintWriter pw = new PrintWriter(bw)) {
               x=new Scanner(new File(path));
               x.useDelimiter("[,\n]");
               while(x.hasNext()){
                   ID=x.next();DATE=x.next();                  
                   NAME1=x.next();PHONE1=x.next();
                   EMAIL1=x.next();STREET1=x.next();
                   CITY1=x.next();MUNI1=x.next();
                   DISTRICT1=x.next();PROVINCE1=x.next();
                   NAME2=x.next();PHONE2=x.next();
                   EMAIL2=x.next();STREET2=x.next();
                   CITY2=x.next();MUNI2=x.next();
                   DISTRICT2=x.next();PROVINCE2=x.next();
                   L=x.next();B=x.next();
                   H=x.next();W=x.next();
                   FEES=x.next();STATUS=x.next();LOCATION=x.next();
                   if(ID.equals(id)){
                       pw.print(ID + "," + DATE+","+NAME1+","+PHONE1+","+EMAIL1+","+STREET1+","+CITY1+","+MUNI1+","+DISTRICT1+","+PROVINCE1+","+
                    NAME2+","+PHONE2+","+EMAIL2+","+STREET2+","+CITY2+","+MUNI2+","+DISTRICT2+","+PROVINCE2+","+L+","+B+","+H+","+W+","+FEES+","+keyword+","+LOCATION+"\n");
                   }
                   else{
                       pw.print(ID + "," + DATE+","+NAME1+","+PHONE1+","+EMAIL1+","+STREET1+","+CITY1+","+MUNI1+","+DISTRICT1+","+PROVINCE1+","+
                    NAME2+","+PHONE2+","+EMAIL2+","+STREET2+","+CITY2+","+MUNI2+","+DISTRICT2+","+PROVINCE2+","+L+","+B+","+H+","+W+","+FEES+","+STATUS+","+LOCATION+"\n");
                   }
               }x.close();
        pw.flush();
        pw.close();
        oldFile.delete();
        
        File dump=new File(path);
        newFile.renameTo(dump);
        
           
        } catch (IOException ex) {
            Logger.getLogger(edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void editdetails(String keyword,String id,String location) throws IOException{
       
        String ID,DATE,NAME1,PHONE1,EMAIL1,STREET1,CITY1,MUNI1,DISTRICT1,PROVINCE1,
                    NAME2,PHONE2,EMAIL2,STREET2,CITY2,MUNI2,DISTRICT2,PROVINCE2,L,B ,H ,W,FEES,STATUS,LOCATION;
        String tempFile="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\temp.txt";
       String path="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt";
        File oldFile = new File(path);
       File newFile=new File(tempFile);
       FileWriter fw;
            fw = new FileWriter(tempFile,true);
            BufferedWriter bw=new BufferedWriter(fw);
           try (PrintWriter pw = new PrintWriter(bw)) {
               x=new Scanner(new File(path));
               x.useDelimiter("[,\n]");
               while(x.hasNext()){
                   ID=x.next();DATE=x.next();                  
                   NAME1=x.next();PHONE1=x.next();
                   EMAIL1=x.next();STREET1=x.next();
                   CITY1=x.next();MUNI1=x.next();
                   DISTRICT1=x.next();PROVINCE1=x.next();
                   NAME2=x.next();PHONE2=x.next();
                   EMAIL2=x.next();STREET2=x.next();
                   CITY2=x.next();MUNI2=x.next();
                   DISTRICT2=x.next();PROVINCE2=x.next();
                   L=x.next();B=x.next();
                   H=x.next();W=x.next();
                   FEES=x.next();STATUS=x.next();LOCATION=x.next();
                   if(ID.equals(id)){
                       pw.print(ID + "," + DATE+","+NAME1+","+PHONE1+","+EMAIL1+","+STREET1+","+CITY1+","+MUNI1+","+DISTRICT1+","+PROVINCE1+","+
                    NAME2+","+PHONE2+","+EMAIL2+","+STREET2+","+CITY2+","+MUNI2+","+DISTRICT2+","+PROVINCE2+","+L+","+B+","+H+","+W+","+FEES+","+keyword+","+location+"\n");
                   }
                   else{
                       pw.print(ID + "," + DATE+","+NAME1+","+PHONE1+","+EMAIL1+","+STREET1+","+CITY1+","+MUNI1+","+DISTRICT1+","+PROVINCE1+","+
                    NAME2+","+PHONE2+","+EMAIL2+","+STREET2+","+CITY2+","+MUNI2+","+DISTRICT2+","+PROVINCE2+","+L+","+B+","+H+","+W+","+FEES+","+STATUS+","+LOCATION+"\n");
                   }
               }x.close();
        pw.flush();
        pw.close();
        oldFile.delete();
        
        File dump=new File(path);
        newFile.renameTo(dump);
        
           
        } catch (IOException ex) {
            Logger.getLogger(edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public String sendDate(){
        SimpleDateFormat formatter=new SimpleDateFormat("dd MM yyyy");
        Date testvar=new Date();
        String giveme=formatter.format(testvar);
        return giveme;
    }
     private Scanner x;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new assignTask().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(assignTask.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton assign;
    private javax.swing.JButton back;
    public javax.swing.JTable detailstable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ordertable;
    public javax.swing.JTextField tosearch;
    public javax.swing.JTextField tosearch1;
    // End of variables declaration//GEN-END:variables
}
