/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orders;

import assignment.success;
import deliveryStaff.acceptOrders;
import deliveryStaff.deliverOrders;
import deliveryStaff.recipet;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.Scanner;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import managingStaff.edit;

/**
 *
 * @author Asus
 */

public class orderplace extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public orderplace() {
        initComponents();
        deliveredbutton.setVisible(false);
        jButtonback1.setVisible(false);
        jLabel18.setVisible(false);
        n1.setVisible(false); n2.setVisible(false); n3.setVisible(false);
        date();
        generateId();  
    }
    public String date(){
        Calendar cal = Calendar.getInstance(); 
        Date d = new Date();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        String date1=sdf1.format(d);
        date.setText(date1);
        return date1;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        orderidjlabel = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        snamejlabel = new javax.swing.JLabel();
        rname = new javax.swing.JTextField();
        emailjlabel = new javax.swing.JLabel();
        rphone = new javax.swing.JTextField();
        detailsjlabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        breadth = new javax.swing.JTextField();
        fees = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        order = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        length = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailjlabel1 = new javax.swing.JLabel();
        remail = new javax.swing.JTextField();
        emailjlabel2 = new javax.swing.JLabel();
        snamejlabel1 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        emailjlabel3 = new javax.swing.JLabel();
        sphone = new javax.swing.JTextField();
        emailjlabel4 = new javax.swing.JLabel();
        semail = new javax.swing.JTextField();
        emailjlabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        sstreet = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        scity = new javax.swing.JTextField();
        smuni = new javax.swing.JTextField();
        sdistrict = new javax.swing.JTextField();
        sprovince = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rcity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rstreet = new javax.swing.JTextField();
        rmuni = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rdistrict = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rprovince = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        deliveredbutton = new javax.swing.JButton();
        n1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        n3 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        jButtonback1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Form");
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(20, 63, 107));

        jLabel1.setBackground(new java.awt.Color(255, 198, 0));
        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 198, 0));
        jLabel1.setText("Order Form");

        orderidjlabel.setBackground(new java.awt.Color(0, 0, 0));
        orderidjlabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        orderidjlabel.setText("Order ID:");

        id.setEditable(false);
        id.setBackground(new java.awt.Color(246, 245, 77));
        id.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Sender Details:");

        snamejlabel.setBackground(new java.awt.Color(0, 0, 0));
        snamejlabel.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        snamejlabel.setText("Name:");

        rname.setBackground(new java.awt.Color(246, 245, 77));
        rname.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        emailjlabel.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        emailjlabel.setText("Phone:");

        rphone.setBackground(new java.awt.Color(246, 245, 77));
        rphone.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rphoneActionPerformed(evt);
            }
        });

        detailsjlabel.setBackground(new java.awt.Color(0, 0, 0));
        detailsjlabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        detailsjlabel.setText("Delivery Details:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel4.setText("Order Length (in cm):");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel5.setText("Order breadth (in cm):");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setText("Order height (in cm):");

        breadth.setBackground(new java.awt.Color(246, 245, 77));
        breadth.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        breadth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        breadth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadthActionPerformed(evt);
            }
        });

        fees.setBackground(new java.awt.Color(246, 245, 77));
        fees.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        fees.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesActionPerformed(evt);
            }
        });

        height.setBackground(new java.awt.Color(246, 245, 77));
        height.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        height.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel7.setText("Fees (in Rs):");

        order.setBackground(new java.awt.Color(254, 177, 57));
        order.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        order.setText("Place order");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });

        jButtonback.setBackground(new java.awt.Color(235, 29, 54));
        jButtonback.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jButtonback.setForeground(new java.awt.Color(254, 177, 57));
        jButtonback.setText("Back");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("Order Date:");

        length.setBackground(new java.awt.Color(246, 245, 77));
        length.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        length.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthActionPerformed(evt);
            }
        });

        date.setEditable(false);
        date.setBackground(new java.awt.Color(246, 245, 77));
        date.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Receiver Details:");

        emailjlabel1.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        emailjlabel1.setText("Email");

        remail.setBackground(new java.awt.Color(246, 245, 77));
        remail.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        remail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        remail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remailActionPerformed(evt);
            }
        });

        emailjlabel2.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        emailjlabel2.setText("Address:");

        snamejlabel1.setBackground(new java.awt.Color(0, 0, 0));
        snamejlabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        snamejlabel1.setText("Name:");

        sname.setBackground(new java.awt.Color(246, 245, 77));
        sname.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        emailjlabel3.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        emailjlabel3.setText("Phone:");

        sphone.setBackground(new java.awt.Color(246, 245, 77));
        sphone.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        sphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphoneActionPerformed(evt);
            }
        });

        emailjlabel4.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        emailjlabel4.setText("Email");

        semail.setBackground(new java.awt.Color(246, 245, 77));
        semail.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        semail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        semail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semailActionPerformed(evt);
            }
        });

        emailjlabel5.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        emailjlabel5.setText("Address:");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel10.setText("Order Weight (in gm):");

        weight.setBackground(new java.awt.Color(246, 245, 77));
        weight.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        weight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });

        sstreet.setBackground(new java.awt.Color(246, 245, 77));
        sstreet.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sstreet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        sstreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sstreetActionPerformed(evt);
            }
        });

        jLabel16.setText("MUNICIPALITY");

        jLabel9.setText("DISTRICT");

        jLabel19.setText("STREET");

        scity.setBackground(new java.awt.Color(246, 245, 77));
        scity.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        scity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        scity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scityActionPerformed(evt);
            }
        });

        smuni.setBackground(new java.awt.Color(246, 245, 77));
        smuni.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        smuni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        smuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smuniActionPerformed(evt);
            }
        });

        sdistrict.setBackground(new java.awt.Color(246, 245, 77));
        sdistrict.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sdistrict.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        sdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdistrictActionPerformed(evt);
            }
        });

        sprovince.setBackground(new java.awt.Color(246, 245, 77));
        sprovince.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sprovince.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        sprovince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprovinceActionPerformed(evt);
            }
        });

        jLabel11.setText("COUNTRY");

        jLabel12.setText("CITY");

        rcity.setBackground(new java.awt.Color(246, 245, 77));
        rcity.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rcity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcityActionPerformed(evt);
            }
        });

        jLabel13.setText("CITY");

        jLabel20.setText("STREET");

        rstreet.setBackground(new java.awt.Color(246, 245, 77));
        rstreet.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rstreet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rstreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstreetActionPerformed(evt);
            }
        });

        rmuni.setBackground(new java.awt.Color(246, 245, 77));
        rmuni.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rmuni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rmuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmuniActionPerformed(evt);
            }
        });

        jLabel17.setText("MUNICIPALITY");

        rdistrict.setBackground(new java.awt.Color(246, 245, 77));
        rdistrict.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rdistrict.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdistrictActionPerformed(evt);
            }
        });

        jLabel14.setText("DISTRICT");

        rprovince.setBackground(new java.awt.Color(246, 245, 77));
        rprovince.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rprovince.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rprovince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rprovinceActionPerformed(evt);
            }
        });

        jLabel15.setText("COUNTRY");

        deliveredbutton.setBackground(new java.awt.Color(254, 177, 57));
        deliveredbutton.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        deliveredbutton.setText("DELIVERED");
        deliveredbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveredbuttonActionPerformed(evt);
            }
        });

        n1.setEditable(false);
        n1.setBackground(new java.awt.Color(246, 245, 77));
        n1.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        n1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel18.setText("Order Date:");

        n3.setEditable(false);
        n3.setBackground(new java.awt.Color(246, 245, 77));
        n3.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        n3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });

        n2.setEditable(false);
        n2.setBackground(new java.awt.Color(246, 245, 77));
        n2.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        n2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });

        jButtonback1.setBackground(new java.awt.Color(235, 29, 54));
        jButtonback1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jButtonback1.setForeground(new java.awt.Color(254, 177, 57));
        jButtonback1.setText("Back");
        jButtonback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonback1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(emailjlabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scity, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(smuni, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(orderidjlabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(snamejlabel1)
                                    .addGap(50, 50, 50)
                                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailjlabel3)
                                        .addComponent(emailjlabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(semail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sprovince, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailjlabel1)
                                        .addComponent(emailjlabel2))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel20)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rcity, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(rmuni, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel17))
                                            .addGap(5, 5, 5)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rprovince, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel15)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(41, 41, 41)
                                            .addComponent(remail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(snamejlabel)
                                        .addComponent(emailjlabel))
                                    .addGap(48, 48, 48)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rphone, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(order)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deliveredbutton)
                                .addGap(282, 282, 282))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButtonback)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(detailsjlabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(length, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(weight))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(breadth, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(865, Short.MAX_VALUE)
                    .addComponent(jButtonback1)
                    .addGap(5, 5, 5)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderidjlabel)
                            .addComponent(jLabel8)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snamejlabel1)
                            .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel3)
                            .addComponent(sphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel4)
                            .addComponent(semail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel5)
                            .addComponent(sstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sprovince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snamejlabel)
                            .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel)
                            .addComponent(rphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel1)
                            .addComponent(remail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailjlabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rmuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rprovince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailsjlabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(breadth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(order, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveredbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(621, Short.MAX_VALUE)
                    .addComponent(jButtonback1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthActionPerformed

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new manageOrders().setVisible(true);
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        BufferedWriter bw=null;
        String ID,DATE,NAME1,PHONE1,EMAIL1,STREET1,CITY1,MUNI1,DISTRICT1,PROVINCE1,
                    NAME2,PHONE2,EMAIL2,STREET2,CITY2,MUNI2,DISTRICT2,PROVINCE2,L,B ,H ,W,FEES;
        try {
            // TODO add your handling code here:
            File file=new File("C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt");
            bw = new BufferedWriter(new FileWriter("C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt",true));
            ID=id.getText();DATE=date.getText();NAME1=sname.getText();PHONE1=sphone.getText();EMAIL1=semail.getText();STREET1=sstreet.getText();
            CITY1=scity.getText();MUNI1=smuni.getText();DISTRICT1=sdistrict.getText();PROVINCE1=sprovince.getText();
            NAME2=rname.getText();PHONE2=rphone.getText();EMAIL2=remail.getText();STREET2=rstreet.getText();
            CITY2=rcity.getText();MUNI2=rmuni.getText();DISTRICT2=rdistrict.getText();PROVINCE2=rprovince.getText();
            L=length.getText();B=breadth.getText();H=height.getText();W=weight.getText();FEES=fees.getText();
            
            String linek = ID + "," + DATE+","+NAME1+","+PHONE1+","+EMAIL1+","+STREET1+","+CITY1+","+MUNI1+","+DISTRICT1+","+PROVINCE1+","+
                    NAME2+","+PHONE2+","+EMAIL2+","+STREET2+","+CITY2+","+MUNI2+","+DISTRICT2+","+PROVINCE2+","+L+","+B+","+H+","+W+","+
                    FEES+","+"toassign"+","+"officeA"+"\n";
            bw.write(linek);
            bw.close();
            recipet();
            
        } catch (IOException ex) {
            Logger.getLogger(orderplace.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(orderplace.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_orderActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void feesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feesActionPerformed

    private void breadthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breadthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_breadthActionPerformed

    private void rphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rphoneActionPerformed

    private void remailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remailActionPerformed

    private void sphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sphoneActionPerformed

    private void semailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semailActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void sstreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sstreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sstreetActionPerformed

    private void scityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scityActionPerformed

    private void smuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smuniActionPerformed

    private void sdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdistrictActionPerformed

    private void sprovinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprovinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sprovinceActionPerformed

    private void rcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcityActionPerformed

    private void rstreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rstreetActionPerformed

    private void rmuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmuniActionPerformed

    private void rdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdistrictActionPerformed

    private void rprovinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rprovinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rprovinceActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n3ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n2ActionPerformed

    private void deliveredbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveredbuttonActionPerformed
        // TODO add your handling code here:

        try {
            String orderid=id.getText();
            assignTask edit=new assignTask();
            edit.editdetails("delivered",orderid,"destination");
            acceptOrders test=new acceptOrders();
            test.edit(orderid,"delivered");
            recipet();
        } catch (IOException ex) {
            Logger.getLogger(orderplace.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deliveredbuttonActionPerformed

    private void jButtonback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonback1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonback1ActionPerformed
 
    public String generateId(){
        int num;
        ArrayList<Integer> list = new ArrayList<>();
        for (int i=1; i<200; i++) list.add(i);
        Collections.shuffle(list);
        for (int i=0; i<1; i++){
            num=list.get(i);
            String id = Integer.toString(num);
            this.id.setText(id);
            this.id.setEditable(false);
            return id;
        }
        return null;
    }
    public void recipet(){
        
            String orderid=id.getText();
            
            String ID,
                    NAME2,PHONE2,EMAIL2,STREET2,CITY2,MUNI2,DISTRICT2,PROVINCE2,PHONE1,SNAME;
            ID=id.getText();
            NAME2=rname.getText();PHONE2=rphone.getText();EMAIL2=remail.getText();STREET2=rstreet.getText();
            CITY2=rcity.getText();MUNI2=rmuni.getText();DISTRICT2=rdistrict.getText();PROVINCE2=rprovince.getText();SNAME=sname.getText();
            PHONE1=sphone.getText();
            
            recipet recipet=new recipet();
            recipet.setVisible(true);
            recipet.pack();
            recipet.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            recipet.id.setText(ID);
            recipet.rname.setText(NAME2);
            recipet.rphone.setText(PHONE2);
            recipet.remail.setText(EMAIL2);
            recipet.rstreet.setText(STREET2);
            recipet.rcity.setText(CITY2);
            recipet.rmuni.setText(MUNI2);
            recipet.rdistrict1.setText(DISTRICT2);
            recipet.rprovince1.setText(PROVINCE2);
            recipet.sname.setText(SNAME);
            recipet.sphone.setText(PHONE1);
            Calendar cal = Calendar.getInstance();     
            Date d = new Date();
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy/MM/dd");
            String date1=sdf1.format(d);
            recipet.date4.setText(date1);
  
    }
    public void test(){
        this.setVisible(false);
        new checkInOrders().setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderplace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField breadth;
    public javax.swing.JTextField date;
    public javax.swing.JButton deliveredbutton;
    private javax.swing.JLabel detailsjlabel;
    private javax.swing.JLabel emailjlabel;
    private javax.swing.JLabel emailjlabel1;
    private javax.swing.JLabel emailjlabel2;
    private javax.swing.JLabel emailjlabel3;
    private javax.swing.JLabel emailjlabel4;
    private javax.swing.JLabel emailjlabel5;
    public javax.swing.JTextField fees;
    public javax.swing.JTextField height;
    public javax.swing.JTextField id;
    public javax.swing.JButton jButtonback;
    public javax.swing.JButton jButtonback1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField length;
    public javax.swing.JTextField n1;
    public javax.swing.JTextField n2;
    public javax.swing.JTextField n3;
    public javax.swing.JButton order;
    private javax.swing.JLabel orderidjlabel;
    public javax.swing.JTextField rcity;
    public javax.swing.JTextField rdistrict;
    public javax.swing.JTextField remail;
    public javax.swing.JTextField rmuni;
    public javax.swing.JTextField rname;
    public javax.swing.JTextField rphone;
    public javax.swing.JTextField rprovince;
    public javax.swing.JTextField rstreet;
    public javax.swing.JTextField scity;
    public javax.swing.JTextField sdistrict;
    public javax.swing.JTextField semail;
    public javax.swing.JTextField smuni;
    public javax.swing.JTextField sname;
    private javax.swing.JLabel snamejlabel;
    private javax.swing.JLabel snamejlabel1;
    public javax.swing.JTextField sphone;
    public javax.swing.JTextField sprovince;
    public javax.swing.JTextField sstreet;
    public javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
