/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orders;

import assignment.error;
import assignment.success;
import deliveryStaff.dashboardDelivery;
import deliveryStaff.deliverOrders;
import deliveryStaff.manageTasks;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import managingStaff.edit;

/**
 *
 * @author bidha
 */
public class searchOrder extends javax.swing.JFrame {
String did;
    /**
     * Creates new form searchOrder
     */
    public searchOrder() {
        initComponents();
        delete.setVisible(false);
        jButtonback1.setVisible(false);
    }

    public searchOrder(String loginid) {
        this.did=loginid;
       initComponents();
        delete.setVisible(false);
        jButtonback1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        orderidjlabel = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        snamejlabel = new javax.swing.JLabel();
        rname = new javax.swing.JTextField();
        emailjlabel = new javax.swing.JLabel();
        rphone = new javax.swing.JTextField();
        detailsjlabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        breadth = new javax.swing.JTextField();
        fees = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonback = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        length = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailjlabel1 = new javax.swing.JLabel();
        remail = new javax.swing.JTextField();
        emailjlabel2 = new javax.swing.JLabel();
        snamejlabel1 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        emailjlabel3 = new javax.swing.JLabel();
        sphone = new javax.swing.JTextField();
        emailjlabel4 = new javax.swing.JLabel();
        semail = new javax.swing.JTextField();
        emailjlabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        sstreet = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        scity = new javax.swing.JTextField();
        smuni = new javax.swing.JTextField();
        sdistrict = new javax.swing.JTextField();
        sprovince = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rcity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rstreet = new javax.swing.JTextField();
        rmuni = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rdistrict = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rprovince = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        deliveredbutton = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jButtonback1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 63, 107));

        jLabel1.setBackground(new java.awt.Color(255, 198, 0));
        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 198, 0));
        jLabel1.setText("ORDERS MANAGEMENT");

        orderidjlabel.setBackground(new java.awt.Color(0, 0, 0));
        orderidjlabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        orderidjlabel.setText("Order ID:");

        id.setBackground(new java.awt.Color(246, 245, 77));
        id.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Sender Details:");

        snamejlabel.setBackground(new java.awt.Color(0, 0, 0));
        snamejlabel.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        snamejlabel.setText("Name:");

        rname.setEditable(false);
        rname.setBackground(new java.awt.Color(246, 245, 77));
        rname.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        emailjlabel.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        emailjlabel.setText("Phone:");

        rphone.setEditable(false);
        rphone.setBackground(new java.awt.Color(246, 245, 77));
        rphone.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rphoneActionPerformed(evt);
            }
        });

        detailsjlabel.setBackground(new java.awt.Color(0, 0, 0));
        detailsjlabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        detailsjlabel.setText("Delivery Details:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel4.setText("Order Length (in cm):");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel5.setText("Order breadth (in cm):");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setText("Order height (in cm):");

        breadth.setEditable(false);
        breadth.setBackground(new java.awt.Color(246, 245, 77));
        breadth.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        breadth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        breadth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadthActionPerformed(evt);
            }
        });

        fees.setEditable(false);
        fees.setBackground(new java.awt.Color(246, 245, 77));
        fees.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        fees.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesActionPerformed(evt);
            }
        });

        height.setEditable(false);
        height.setBackground(new java.awt.Color(246, 245, 77));
        height.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        height.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel7.setText("Fees (in Rs):");

        jButtonback.setBackground(new java.awt.Color(235, 29, 54));
        jButtonback.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jButtonback.setForeground(new java.awt.Color(254, 177, 57));
        jButtonback.setText("Back");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("Order Date:");

        length.setEditable(false);
        length.setBackground(new java.awt.Color(246, 245, 77));
        length.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        length.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthActionPerformed(evt);
            }
        });

        date.setEditable(false);
        date.setBackground(new java.awt.Color(246, 245, 77));
        date.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Receiver Details:");

        emailjlabel1.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        emailjlabel1.setText("Email");

        remail.setEditable(false);
        remail.setBackground(new java.awt.Color(246, 245, 77));
        remail.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        remail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        remail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remailActionPerformed(evt);
            }
        });

        emailjlabel2.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        emailjlabel2.setText("Address:");

        snamejlabel1.setBackground(new java.awt.Color(0, 0, 0));
        snamejlabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        snamejlabel1.setText("Name:");

        sname.setEditable(false);
        sname.setBackground(new java.awt.Color(246, 245, 77));
        sname.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        emailjlabel3.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        emailjlabel3.setText("Phone:");

        sphone.setEditable(false);
        sphone.setBackground(new java.awt.Color(246, 245, 77));
        sphone.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        sphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphoneActionPerformed(evt);
            }
        });

        emailjlabel4.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        emailjlabel4.setText("Email");

        semail.setEditable(false);
        semail.setBackground(new java.awt.Color(246, 245, 77));
        semail.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        semail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        semail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semailActionPerformed(evt);
            }
        });

        emailjlabel5.setBackground(new java.awt.Color(0, 0, 0));
        emailjlabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        emailjlabel5.setText("Address:");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel10.setText("Order Weight (in gm):");

        weight.setEditable(false);
        weight.setBackground(new java.awt.Color(246, 245, 77));
        weight.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        weight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });

        sstreet.setEditable(false);
        sstreet.setBackground(new java.awt.Color(246, 245, 77));
        sstreet.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sstreet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        sstreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sstreetActionPerformed(evt);
            }
        });

        jLabel16.setText("MUNICIPALITY");

        jLabel9.setText("DISTRICT");

        jLabel19.setText("STREET");

        scity.setEditable(false);
        scity.setBackground(new java.awt.Color(246, 245, 77));
        scity.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        scity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        scity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scityActionPerformed(evt);
            }
        });

        smuni.setEditable(false);
        smuni.setBackground(new java.awt.Color(246, 245, 77));
        smuni.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        smuni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        smuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smuniActionPerformed(evt);
            }
        });

        sdistrict.setEditable(false);
        sdistrict.setBackground(new java.awt.Color(246, 245, 77));
        sdistrict.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sdistrict.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        sdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdistrictActionPerformed(evt);
            }
        });

        sprovince.setEditable(false);
        sprovince.setBackground(new java.awt.Color(246, 245, 77));
        sprovince.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        sprovince.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        sprovince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprovinceActionPerformed(evt);
            }
        });

        jLabel11.setText("COUNTRY");

        jLabel12.setText("CITY");

        rcity.setEditable(false);
        rcity.setBackground(new java.awt.Color(246, 245, 77));
        rcity.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rcity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcityActionPerformed(evt);
            }
        });

        jLabel13.setText("CITY");

        jLabel20.setText("STREET");

        rstreet.setEditable(false);
        rstreet.setBackground(new java.awt.Color(246, 245, 77));
        rstreet.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rstreet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rstreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstreetActionPerformed(evt);
            }
        });

        rmuni.setEditable(false);
        rmuni.setBackground(new java.awt.Color(246, 245, 77));
        rmuni.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rmuni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rmuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmuniActionPerformed(evt);
            }
        });

        jLabel17.setText("MUNICIPALITY");

        rdistrict.setEditable(false);
        rdistrict.setBackground(new java.awt.Color(246, 245, 77));
        rdistrict.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rdistrict.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdistrictActionPerformed(evt);
            }
        });

        jLabel14.setText("DISTRICT");

        rprovince.setEditable(false);
        rprovince.setBackground(new java.awt.Color(246, 245, 77));
        rprovince.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        rprovince.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        rprovince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rprovinceActionPerformed(evt);
            }
        });

        jLabel15.setText("COUNTRY");

        deliveredbutton.setBackground(new java.awt.Color(254, 177, 57));
        deliveredbutton.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        deliveredbutton.setForeground(new java.awt.Color(0, 0, 0));
        deliveredbutton.setText("SEARCH");
        deliveredbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveredbuttonActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(254, 177, 57));
        delete.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("CANCEL");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel18.setText("Status:");

        status.setEditable(false);
        status.setBackground(new java.awt.Color(246, 245, 77));
        status.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel21.setText("Location:");

        location.setEditable(false);
        location.setBackground(new java.awt.Color(246, 245, 77));
        location.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        location.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        jButtonback1.setBackground(new java.awt.Color(235, 29, 54));
        jButtonback1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jButtonback1.setForeground(new java.awt.Color(254, 177, 57));
        jButtonback1.setText("Back");
        jButtonback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonback1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(orderidjlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(snamejlabel1)
                                        .addGap(50, 50, 50)
                                        .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailjlabel3)
                                            .addComponent(emailjlabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(semail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deliveredbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(emailjlabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scity, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(smuni, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sprovince, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailjlabel1)
                                .addComponent(emailjlabel2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(remail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel20)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rcity, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(rmuni, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel17))
                                            .addGap(5, 5, 5)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rprovince, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(snamejlabel)
                                .addComponent(emailjlabel))
                            .addGap(48, 48, 48)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rphone, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(83, 83, 83)
                                .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonback)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(detailsjlabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(length, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(weight))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(breadth, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(83, 83, 83)
                                        .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(83, 83, 83)
                                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(899, Short.MAX_VALUE)
                    .addComponent(jButtonback1)
                    .addGap(5, 5, 5)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderidjlabel)
                            .addComponent(deliveredbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snamejlabel1)
                            .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel3)
                            .addComponent(sphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel4)
                            .addComponent(semail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel5)
                            .addComponent(sstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sprovince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snamejlabel)
                            .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel)
                            .addComponent(rphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjlabel1)
                            .addComponent(remail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailjlabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rmuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rprovince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailsjlabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(breadth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(619, Short.MAX_VALUE)
                    .addComponent(jButtonback1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rphoneActionPerformed

    private void breadthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breadthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_breadthActionPerformed

    private void feesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feesActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
       new manageOrders().setVisible(true);this.setVisible(false);
       
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void remailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remailActionPerformed

    private void sphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sphoneActionPerformed

    private void semailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semailActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void sstreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sstreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sstreetActionPerformed

    private void scityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scityActionPerformed

    private void smuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smuniActionPerformed

    private void sdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdistrictActionPerformed

    private void sprovinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprovinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sprovinceActionPerformed

    private void rcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcityActionPerformed

    private void rstreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rstreetActionPerformed

    private void rmuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmuniActionPerformed

    private void rdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdistrictActionPerformed

    private void rprovinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rprovinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rprovinceActionPerformed

    private void deliveredbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveredbuttonActionPerformed
        
      
        try {
            String orderid=id.getText();
            search(orderid);
        } catch (FileNotFoundException ex) {
            new error().setVisible(true);
            Logger.getLogger(searchOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deliveredbuttonActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String orderid=id.getText();
        delete(orderid);   
    }//GEN-LAST:event_deleteActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void jButtonback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonback1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new dashboardDelivery(did).setVisible(true);
    }//GEN-LAST:event_jButtonback1ActionPerformed
public void search(String oid) throws FileNotFoundException{
    
boolean found=false;
                
                x=new Scanner(new File("C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt"));
                x.useDelimiter("[,\n]");
                while(x.hasNext()&&!found){
                    String ID=x.next();
                    String DATE=  x.next(); 
                    String SNAME=x.next();
                    String SPHONE=x.next();   
                    String SEMAIL=   x.next();  
                    String SSTREET=  x.next();  
                    String STOWN=   x.next(); 
                    String SMUNI=   x.next(); 
                    String SDISTRICT=  x.next(); 
                    String SPROVINCE=  x.next();  
                    String RNAME=   x.next(); 
                    String RPHONE=   x.next(); 
                    String REMAIL=   x.next(); 
                    String RSTREET=  x.next(); 
                    String RTOWN=   x.next(); 
                    String RMUNI=   x.next(); 
                    String RDISTRICT=   x.next(); 
                    String RPROVINCE=   x.next(); 
                    String L=  x.next(); 
                    String B=   x.next(); 
                    String H=   x.next(); 
                    String W=   x.next(); 
                    String FEES=   x.next(); 
                    String STATUS=  x.next();  
                    String LOCATION=   x.next(); 
                    if(ID.equals(oid)){
                            
                            
                            
                             id.setText(ID);
                             date.setText(DATE); date.setEditable(false);
                             sname.setText(SNAME); sname.setEditable(false);
                             sphone.setText(SPHONE); sphone.setEditable(false);
                             semail.setText(SEMAIL); semail.setEditable(false);
                             sstreet.setText(SSTREET); sstreet.setEditable(false);
                             scity.setText(STOWN); scity.setEditable(false);
                             sdistrict.setText(SDISTRICT); sdistrict.setEditable(false);
                             sprovince.setText(SPROVINCE); sprovince.setEditable(false);
                             rmuni.setText(RMUNI); rmuni.setEditable(false);
                             rname.setText(RNAME); rname.setEditable(false);
                             smuni.setText(SMUNI); smuni.setEditable(false);
                             rphone.setText(RPHONE); rphone.setEditable(false);
                             remail.setText(REMAIL); remail.setEditable(false);
                             rstreet.setText(RSTREET); rcity.setEditable(false);
                             rcity.setText(RTOWN); rdistrict.setEditable(false);
                             rdistrict.setText(RDISTRICT); rcity.setEditable(false);
                             rprovince.setText(RPROVINCE); rprovince.setEditable(false);
                             rmuni.setText(RMUNI); rmuni.setEditable(false);
                             length.setText(L); length.setEditable(false);
                             breadth.setText(B); breadth.setEditable(false);
                             height.setText(H); height.setEditable(false);
                             weight.setText(W); weight.setEditable(false);
                             fees.setText(FEES); fees.setEditable(false);
                             status.setText(STATUS); status.setEditable(false);
                             location.setText(LOCATION); location.setEditable(false);
                    }
                }x.close();
                
    }
    public void delete(String oid){
        String ID,DATE,NAME1,PHONE1,EMAIL1,STREET1,CITY1,MUNI1,DISTRICT1,PROVINCE1,
                    NAME2,PHONE2,EMAIL2,STREET2,CITY2,MUNI2,DISTRICT2,PROVINCE2,L,B ,H ,W,FEES,STATUS,LOCATION;
        String tempFile="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\managingStaff\\temp.txt";
        String delFile="C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\managingStaff\\deletedorders.txt";
          try {
                FileWriter fw=new FileWriter(tempFile,true);FileWriter fw1=new FileWriter(delFile,true);
                BufferedWriter bw=new BufferedWriter(fw);BufferedWriter bw1=new BufferedWriter(fw1);
                PrintWriter pw=new PrintWriter(bw);PrintWriter pw1=new PrintWriter(bw1);
                x=new Scanner(new File("C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt"));
               x.useDelimiter("[,\n]");
                File newFile=new File(tempFile);
                File newFile2=new File(delFile);
               File oldFile  = new File("C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt");
                while(x.hasNext()){
                   ID=x.next();DATE=x.next();                  
                   NAME1=x.next();PHONE1=x.next();
                   EMAIL1=x.next();STREET1=x.next();
                   CITY1=x.next();MUNI1=x.next();
                   DISTRICT1=x.next();PROVINCE1=x.next();
                   NAME2=x.next();PHONE2=x.next();
                   EMAIL2=x.next();STREET2=x.next();
                   CITY2=x.next();MUNI2=x.next();
                   DISTRICT2=x.next();PROVINCE2=x.next();
                   L=x.next();B=x.next();
                   H=x.next();W=x.next();
                   FEES=x.next();STATUS=x.next();LOCATION=x.next();
           
                   if(oid.equals(ID)){
                        pw1.print(ID + "," + date()+","+NAME1+","+PHONE1+","+EMAIL1+","+STREET1+","+CITY1+","+MUNI1+","+DISTRICT1+","+PROVINCE1+","+
                    NAME2+","+PHONE2+","+EMAIL2+","+STREET2+","+CITY2+","+MUNI2+","+DISTRICT2+","+PROVINCE2+","+L+","+B+","+H+","+W+","+FEES+","+STATUS+","+LOCATION+"\n");
                    }
                    else{
                        pw.print(ID + "," + DATE+","+NAME1+","+PHONE1+","+EMAIL1+","+STREET1+","+CITY1+","+MUNI1+","+DISTRICT1+","+PROVINCE1+","+
                    NAME2+","+PHONE2+","+EMAIL2+","+STREET2+","+CITY2+","+MUNI2+","+DISTRICT2+","+PROVINCE2+","+L+","+B+","+H+","+W+","+FEES+","+STATUS+","+LOCATION+"\n");
                }}x.close();
                pw.flush();
                pw.close();
                pw1.flush();
                pw1.close();
                oldFile.delete();
                File dump=new File("C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt");
                newFile.renameTo(dump);
                new success().setVisible(true);
           
                
            } catch (IOException ex) {
                new error().setVisible(true);
                Logger.getLogger(edit.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
        
        }
     public String date(){
        Calendar cal = Calendar.getInstance(); 
        Date d = new Date();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        String date1=sdf1.format(d);
        date.setText(date1);
        return date1;
        
    }
    private Scanner y;
    private Scanner x;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField breadth;
    public javax.swing.JTextField date;
    public javax.swing.JButton delete;
    public javax.swing.JButton deliveredbutton;
    private javax.swing.JLabel detailsjlabel;
    private javax.swing.JLabel emailjlabel;
    private javax.swing.JLabel emailjlabel1;
    private javax.swing.JLabel emailjlabel2;
    private javax.swing.JLabel emailjlabel3;
    private javax.swing.JLabel emailjlabel4;
    private javax.swing.JLabel emailjlabel5;
    public javax.swing.JTextField fees;
    public javax.swing.JTextField height;
    public javax.swing.JTextField id;
    public javax.swing.JButton jButtonback;
    public javax.swing.JButton jButtonback1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField length;
    public javax.swing.JTextField location;
    private javax.swing.JLabel orderidjlabel;
    public javax.swing.JTextField rcity;
    public javax.swing.JTextField rdistrict;
    public javax.swing.JTextField remail;
    public javax.swing.JTextField rmuni;
    public javax.swing.JTextField rname;
    public javax.swing.JTextField rphone;
    public javax.swing.JTextField rprovince;
    public javax.swing.JTextField rstreet;
    public javax.swing.JTextField scity;
    public javax.swing.JTextField sdistrict;
    public javax.swing.JTextField semail;
    public javax.swing.JTextField smuni;
    public javax.swing.JTextField sname;
    private javax.swing.JLabel snamejlabel;
    private javax.swing.JLabel snamejlabel1;
    public javax.swing.JTextField sphone;
    public javax.swing.JTextField sprovince;
    public javax.swing.JTextField sstreet;
    public javax.swing.JTextField status;
    public javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
