/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orders;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author bidha
 */
public class trackOrders extends javax.swing.JFrame {

    /**
     * Creates new form trackOrders
     */
    public trackOrders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonback = new javax.swing.JButton();
        orderidjlabel = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButtonback1 = new javax.swing.JButton();
        orderidjlabel1 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 63, 107));

        jLabel4.setBackground(new java.awt.Color(255, 198, 0));
        jLabel4.setFont(new java.awt.Font("Poppins ExtraBold", 0, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 198, 0));
        jLabel4.setText("TRACK ORDERS");

        jButtonback.setBackground(new java.awt.Color(235, 29, 54));
        jButtonback.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jButtonback.setForeground(new java.awt.Color(254, 177, 57));
        jButtonback.setText("Back");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        orderidjlabel.setBackground(new java.awt.Color(0, 0, 0));
        orderidjlabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        orderidjlabel.setText("Order ID:");

        id.setBackground(new java.awt.Color(246, 245, 77));
        id.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButtonback1.setBackground(new java.awt.Color(254, 177, 57));
        jButtonback1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jButtonback1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonback1.setText("SEARCH");
        jButtonback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonback1ActionPerformed(evt);
            }
        });

        orderidjlabel1.setBackground(new java.awt.Color(0, 0, 0));
        orderidjlabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        orderidjlabel1.setText("Location:");

        location.setEditable(false);
        location.setBackground(new java.awt.Color(246, 245, 77));
        location.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        location.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel4)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(orderidjlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonback1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(orderidjlabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(location)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonback)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderidjlabel)
                    .addComponent(jButtonback1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderidjlabel1))
                .addGap(18, 18, 18)
                .addComponent(jButtonback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new manageOrders().setVisible(true);
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jButtonback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonback1ActionPerformed
        // TODO add your handling code here:
        String orderId=id.getText();
        boolean found=false;
                
        try {
            x=new Scanner(new File("C:\\Users\\bidha\\OneDrive\\Documents\\NetBeansProjects\\hw1\\src\\main\\java\\orders\\orderdetails.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(trackOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
                x.useDelimiter("[,\n]");
                while(x.hasNext()&&!found){
                    String ID=x.next();
                    String DATE=  x.next();  
                    String SNAME=x.next();
                    String SPHONE=x.next();   
                    String SEMAIL=   x.next();  
                    String SSTREET=  x.next();  
                    String STOWN=   x.next(); 
                    String SMUNI=   x.next(); 
                    String SDISTRICT=  x.next(); 
                    String SPROVINCE=  x.next();  
                    String RNAME=   x.next(); 
                    String RPHONE=   x.next(); 
                    String REMAIL=   x.next(); 
                    String RSTREET=  x.next(); 
                    String RTOWN=   x.next(); 
                    String RMUNI=   x.next(); 
                    String RDISTRICT=   x.next(); 
                    String RPROVINCE=   x.next(); 
                    String L=  x.next(); 
                    String B=   x.next(); 
                    String H=   x.next(); 
                    String W=   x.next(); 
                    String FEES=   x.next(); 
                    String STATUS=  x.next();  
                    String LOCATION=   x.next();
                   
                    if(ID.equals(orderId)){
                        switch(LOCATION){
                            case"officeA":
                               
                                location.setText("Your order has been placed on "+DATE);
                                break;
                            case"warehouseA":
                                location.setText("Your order has reached 1st warehouse on"+DATE);
                                break;
                            case"shipping":
                                location.setText("Your order is being shipped on "+DATE);   
                                break;
                            case"warehouseB":
                                location.setText("Your order has reached your city warehouse on "+DATE);
                                break;
                            case"officeB":
                                location.setText("Your order has reached your city office on"+DATE);
                                break;
                            case"deliverystart":
                                location.setText("Your order's delivery has been started on "+DATE);
                                break;
                        }
                        
                    }}
        
    }//GEN-LAST:event_jButtonback1ActionPerformed
    private Scanner x;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trackOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trackOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trackOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trackOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trackOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField id;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonback1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField location;
    private javax.swing.JLabel orderidjlabel;
    private javax.swing.JLabel orderidjlabel1;
    // End of variables declaration//GEN-END:variables
}
